import manifest from './image-manifest.json';

interface ImageInfo {
  thumb: string;
  width?: number;
  height?: number;
}

const IMAGES = manifest as Record<string, ImageInfo>;

/** Small WebP version of a portfolio photo (generated by `pnpm thumbs`), with its original size. */
export function getImageInfo(src: string): ImageInfo {
  return IMAGES[src] ?? { thumb: src };
}
